name: Status Update

on:
  workflow_dispatch:
  schedule:
    # Once a day at 8 AM
    - cron: 0 22 * * *
  push:
    branches:
      - main

jobs:
  updates:
    name: Updates
    runs-on: ubuntu-latest
    steps:
      - name: Update my status
        uses: actions/github-script@v2
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            const query = `mutation changeUserStatus ($input: ChangeUserStatusInput!) {
              changeUserStatus (input: $input) {
                status {
                  emoji
                  message
                }
              }
            }`

            const days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
            const dayIndex = (new Date()).getDay()

            github.graphql(query, {
              input: {
                emoji: '👋',
                message: `Hello, happy ${days[dayIndex]}!`
              }
            })
